### ISSUE TITLE
API doc update required.

### ISSUE THREAD

**Issue by rolandsusans** [baloise/corellia#105]
## Expected Behavior
API doc update required. 

Currently, the Contract object has date properties, and API docs are missing time zone information in which date should be send. 

1. I suggest using UTC timezone. 

I suggest:
- `creationDate` - the day the contract was issued. ISO 8601 UTC.
- `startDate` -  Start of contract which means start of insurance coverage. ISO 8601 UTC.
- `endDate` - End of contract which means end of insurance coverage. ISO 8601 UTC.

Btw, supporting hours and minutes - would make sense and make data more precise. 
E.g. sending date as `2019-12-17T10:28:21Z`

**Comment by MarkusTiede** [comment]
Hi @rolandsusans thanks for noticing! We'll check when these clarifications can be implemented.

**Comment by danielgrob** [comment]
Hi Rolands,

The date properties in the contract object are really date properties and not datetime properties. And for dates the timezone does not matter. If my contract starts on 2019-12-17 then it starts on that date independent of the timezone.

Therefore I close that issue as won't fix.

Regards Dany

**Comment by rolandsusans** [comment]
Let me explain more, e.g.:


Date in the time zone ( UTC ): `2019-12-16:23:12:34`
Date in the time zone ( Europe/Zurich ): `2019-12-17:00:12:34`

^ Both of the date times are same, but because of time zone looks different. 


In which time zone date ` 2019-12-17` should be specified? 
Is it UTC date or some other date in the timezone - if so in which time zone it should be specified?

**Comment by danielgrob** [comment]
Hi @rolandsusans,

Again, `creationDate`, `startDate`, and `endDate` are pure date properties. There is no time part in these properties, therefore there is no timezone as well.

You can compare the beforementioned date properties to a birthdate. My birthdate is `1970-11-25` and independent of the timezone I am in, it is always '1970-11-25'.

Is this ok for you?

Regards Dany

**Comment by rolandsusans** [comment]
@danielgrob Can we assume that your server `creationDate`, `startDate`, and `endDate` is in `Europe/Zurich` timezone?

**Comment by danielgrob** [comment]
@rolandsusans Just send the dates that you print on the policy and everything is fine.
