### ISSUE TITLE
Support idempotency - add mandatory eventId to Request

### ISSUE THREAD

**Issue by frank-baier** [baloise/corellia#29]
We propose to add an eventId which has to be unique per event. 

According to the Zalando REST API Guidelines 
https://opensource.zalando.com/restful-api-guidelines/#211
We would like to follow this recommendation for ease of communication and explicit idempotency reasons.

**Comment by rolandsusans** [comment]
Sounds like a good idea. 

We can generate those Idempotency keys like:
- for `{{url}}/corellia/api/insurance/contracts/v1/documents`: <contractId>_<receipt|contract> ( fe. TEST-MHT_receipt, TEST-MHT_contract ) 
- for `{{url}}/corellia/api/insurance/contracts/v1/ `: <contractId>_contract ( fe TEST-MHT_contract )
^ that should do the trick.

Are you planning to implement as HTTP request header: `Idempotency-Key: <key>`?

**Comment by rolandsusans** [comment]
can we use one `Idempotency-Key: <key>` per all 3 requests?

**Comment by frank-baier** [comment]
the goal is to have a unique identification for **A** request (for idempotency and communication reasons).  this results in the requirement, that each event (request) must have its own unique requestId. We propose following the Zalando guide to use a UUID

**Comment by frank-baier** [comment]
this eventId will be a header parameter.

**Comment by rolandsusans** [comment]
> the goal is to have a unique identification for **A** request (for idempotency and communication reasons). this results in the requirement, that each event (request) must have its own unique requestId. We propose following the Zalando guide to use a UUID

can we assume that you are expecting Idempotency-Key as ([RFC4122](https://tools.ietf.org/html/rfc4122)) formatted string?

**Comment by MarkusTiede** [comment]
@frank-baier : can we resolve and close this ticket? (IMHO: yes)

**Comment by frank-baier** [comment]
As answer to Rolands comment, regarding RFC4122: 
yes as described above a UUID per request is fine.
Please be aware that for one contract with two documents we have three requests altogether, which means, that we have three different UUIDs.
