### ISSUE TITLE
Support caller identification - add unique caller id

### ISSUE THREAD

**Issue by frank-baier** [baloise/corellia#30]
We want to be able to identify the caller clearly and simply. 
Therefore we propose to add a unique caller id field on the request structure.
The unique caller id will be determined by the callee (in our case Basler).

**Comment by rolandsusans** [comment]
As I understand this is required for separation of test/live data.

How about putting that **unique caller id** in the request headers 
`X-Requester-Id`:`<your-identification>`?

**Comment by MarkusTiede** [comment]
@frank-baier : can we resolve and close this ticket? (IMHO: yes)
