### ISSUE TITLE
Simplify role model - remove person and company from payment

### ISSUE THREAD

**Issue by frank-baier** [baloise/corellia#31]
Due to an evolvement in business requirements we would like to remove Person and Company from the Payment entity.

As by this change the Payment entity now only will consist of one field, we propose to remove the entire payment entity and to pull up the paymentCode to Contract level.

**Comment by rolandsusans** [comment]
Yeah sure - works for us. 
( When all these micro changes are done will be nice to see new sample payload ).

**Comment by MarkusTiede** [comment]
Thank @rolandsusans for noticing: I've filed #41 to address this.
