### ISSUE TITLE
Align ErrorResponse with HTTP status codes

### ISSUE THREAD

**Issue by schlijo** [baloise/corellia#55]
The http status codes 
https://www.restapitutorial.com/httpstatuscodes.html
are the main indicator for error analysis.
To make it easier to distinguish errors we want to change the ErrorCause in our ErrorResponse as follows:

So far we had 2 Causes:
- **badRequest**
- **inputValidation**

We want to change that to
- **httpClientError** -> Errors like wrong formatted json, or related to message body handling errors of our rest library, except validation errors
- **httpClientErrorInputValidation** -> It's a httpClientError but because it's a validation problem we treat this different (structured validation error messages).
- **httpServerError** -> Some other cause beside of messagebody handling and validation, not data related.

This means inputValidation will have httpClientErrorInputValidation as cause and badRequest will have httpClientError or httpServerError as cause.

This will reflect the http status codes 4xx to httpClientError  and 5xx to httpServerError.
Before badRequest coud be 4xx or 5xxx.

**Comment by dweber019** [comment]
PR merged
