### ISSUE TITLE
Enable sending companies without UID

### ISSUE THREAD

**Issue by dweber019** [baloise/corellia#57]
## Expected Behavior
The only information missing for a company to be processed automatically without providing a UID is the legal form information.

## Actual Behavior
Currently a company has to provide a UID to be found and processed by our systems.

## Implementation
Add field legalForm to the company model.

The field should be validated. Either the UID or the other information incl. legalForm should be available.

The valid values for this field is the crediForm list:

Code | Description
-- | --
01 | Privatperson
10 | Einzelunternehmen
15 | Gewerbebetrieb
20 | Einfache Gesellschaft
21 | Kollektivgesellschaft
22 | Kommanditgesellschaft
23 | Treuhänderschaft/Treuunternehmen
25 | Erbengemeinschaft
29 | Europäische Gesellschaft
30 | Genossenschaft
31 | Aktiengesellschaft
32 | Kommandit Aktiengesellschaft
33 | GmbH
34 | Stiftung
36 | Verein
38 | Anstalt LI
40 | Formloser Bericht
41 | Zweigniederl. ausländ.Gesellsch.
55 | Institut des öffentl. Rechts

**Comment by frank-baier** [comment]
reopened as openapi and swagger.json regenerate where missing.
