### ISSUE TITLE
Extend contract API to conform to LW use cases

### ISSUE THREAD

**Issue by dweber019** [baloise/corellia#88]
The following field have to be added to the create contract API endpoint.

Fields
- transaction
-- type
-- reason
-- effective (optional)
- contract
-- id (was the contractId before)
-- type
- termsOfService
-- type
-- year
- payment
-- code (was the paymentCode before)
-- recurringType
-- dueDate (optional)
- stampTax
- product.coverables.riskLocation
- roles.role

Example JSON
```json
{
	...
	"transaction": {
		"type": 21,
		"reason": 51,
		"effective": "2019-11-07"
	},
	"contract": {
		"id": "EXT-TEST-001",
		"type": "EXT"
	},
	"termsOfService": {
		"type": 1368,
		"year": 2019
	},
	"payment": {
		"code": 1234,
		"recurringType": 211,
		"dueDate": "2019-11-07"
	},
	"stampTaxCode": 1801,
        "products": [
                ...
                "coverables": [
                        {
                                ...
                                "riskLocation": {
                                        "street": "Gartenstrasse",
                                        "houseNumber": "95",
                                        "zipCode": "4052",
                                        "city": "Basel"
                                }
                        }
                ]
                ...
        ],
        "roles": [
                {
                        "partnerNr": "any-partner-nr"
                }
        ]
	...
}
```

**Comment by StephanSST** [comment]
I think 'tos' is not the best name possible. What does it stand for (AGB in german, I know)? But whats the translation? Isn't there a better name for this?

**Comment by dweber019** [comment]
@StephanSST what would you suggest? Only other thing would be write it out like "termsOfService".

**Comment by StephanSST** [comment]
I would use 'termsOfService' as a self-explanatory term

**Comment by dweber019** [comment]
Issues updated with "termsOfService".

**Comment by dweber019** [comment]
Hi @matthewwardle
We will update the endpoint for creating contracts but there will be a new version 2 for this change. For your integration nothing changes for now and you can still use version 1. Goal would be that you migrate in the near future.

**Comment by matthewwardle** [comment]
Hi @dweber019 

Could you let us know when the v2 is final, as then we can scope the change required.

Cheers,
Matt

**Comment by MarkusTiede** [comment]
Assuming this is all done - as it went to production a couple of weeks ago. Setting status accordingly.
